<!DOCTYPE html><html><head>   <meta>     <title>VS Code users: is anyone seeing more errors being reported by Pylance now?</title>   </meta>   <style>
.youtube_player_container {
    position: relative;
    width: 50%;
    padding-bottom: 26.25%;
    /* background-color: yellow; */
}
.youtube_player_frame {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    border: 0;
}
       </style></head><body><a href="index.html"><h2>Index</h2></a><a href="https://www.reddit.com/r/django/comments/1fespjl/vs_code_users_is_anyone_seeing_more_errors_being"><h1>[1139225] VS Code users: is anyone seeing more errors being reported by Pylance now?</h1></a><div>https://www.reddit.com/r/django/.rss</div><div>2024-09-13 14:41:02.458695+00:00</div><div><pre><!-- SC_OFF --><div><p>As an example, have a look at this model:</p> <pre><code>class Comment(models.Model): post = models.ForeignKey(Post, on_delete=models.CASCADE) user = models.ForeignKey(User, on_delete=models.CASCADE) body = models.TextField() status = models.CharField( max_length=1, choices=( ("r", "Needs Review"), ("a", "Approved"), ), ) created = models.DateTimeField(auto_now_add=True) class Meta: ordering = ("-pk",) def __str__(self): return f"{self.get_status_display()}: comment by {self.user}" </code></pre> <p>Previously, Visual Studio Code didn't report any errors with this, but now it has <code>get_status_display</code> underlined in red and considers it an error. When I hover over it, it says:</p> <pre><code>Cannot access attribute "get_status_display" for class "Comment*" Attribute "get_status_display" is unknown Pylance(reportAttributeAccessIssue) </code></pre> &lt;/di</div></pre></div></body></html>